// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"encoding/json"
	"fmt"
)

// DiscordInteraction defines model for DiscordInteraction.
type DiscordInteraction struct {
	Data                 *map[string]interface{} `json:"data,omitempty"`
	Id                   *string                 `json:"id,omitempty"`
	Token                *string                 `json:"token,omitempty"`
	Type                 int                     `json:"type"`
	AdditionalProperties map[string]interface{}  `json:"-"`
}

// JellyfinWebhook defines model for JellyfinWebhook.
type JellyfinWebhook struct {
	Event                *string                `json:"Event,omitempty"`
	EventId              *string                `json:"EventId,omitempty"`
	ItemId               *string                `json:"ItemId,omitempty"`
	Name                 *string                `json:"Name,omitempty"`
	NotificationId       *string                `json:"NotificationId,omitempty"`
	NotificationType     *string                `json:"NotificationType,omitempty"`
	ServerId             *string                `json:"ServerId,omitempty"`
	UserId               *string                `json:"UserId,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PostDiscordInteractionsJSONRequestBody defines body for PostDiscordInteractions for application/json ContentType.
type PostDiscordInteractionsJSONRequestBody = DiscordInteraction

// PostWebhooksJellyfinJSONRequestBody defines body for PostWebhooksJellyfin for application/json ContentType.
type PostWebhooksJellyfinJSONRequestBody = JellyfinWebhook

// Getter for additional properties for DiscordInteraction. Returns the specified
// element and whether it was found
func (a DiscordInteraction) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DiscordInteraction
func (a *DiscordInteraction) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DiscordInteraction to handle AdditionalProperties
func (a *DiscordInteraction) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &a.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
		delete(object, "token")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DiscordInteraction to handle AdditionalProperties
func (a DiscordInteraction) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Data != nil {
		object["data"], err = json.Marshal(a.Data)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'data': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	if a.Token != nil {
		object["token"], err = json.Marshal(a.Token)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'token': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for JellyfinWebhook. Returns the specified
// element and whether it was found
func (a JellyfinWebhook) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for JellyfinWebhook
func (a *JellyfinWebhook) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for JellyfinWebhook to handle AdditionalProperties
func (a *JellyfinWebhook) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["Event"]; found {
		err = json.Unmarshal(raw, &a.Event)
		if err != nil {
			return fmt.Errorf("error reading 'Event': %w", err)
		}
		delete(object, "Event")
	}

	if raw, found := object["EventId"]; found {
		err = json.Unmarshal(raw, &a.EventId)
		if err != nil {
			return fmt.Errorf("error reading 'EventId': %w", err)
		}
		delete(object, "EventId")
	}

	if raw, found := object["ItemId"]; found {
		err = json.Unmarshal(raw, &a.ItemId)
		if err != nil {
			return fmt.Errorf("error reading 'ItemId': %w", err)
		}
		delete(object, "ItemId")
	}

	if raw, found := object["Name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'Name': %w", err)
		}
		delete(object, "Name")
	}

	if raw, found := object["NotificationId"]; found {
		err = json.Unmarshal(raw, &a.NotificationId)
		if err != nil {
			return fmt.Errorf("error reading 'NotificationId': %w", err)
		}
		delete(object, "NotificationId")
	}

	if raw, found := object["NotificationType"]; found {
		err = json.Unmarshal(raw, &a.NotificationType)
		if err != nil {
			return fmt.Errorf("error reading 'NotificationType': %w", err)
		}
		delete(object, "NotificationType")
	}

	if raw, found := object["ServerId"]; found {
		err = json.Unmarshal(raw, &a.ServerId)
		if err != nil {
			return fmt.Errorf("error reading 'ServerId': %w", err)
		}
		delete(object, "ServerId")
	}

	if raw, found := object["UserId"]; found {
		err = json.Unmarshal(raw, &a.UserId)
		if err != nil {
			return fmt.Errorf("error reading 'UserId': %w", err)
		}
		delete(object, "UserId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for JellyfinWebhook to handle AdditionalProperties
func (a JellyfinWebhook) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Event != nil {
		object["Event"], err = json.Marshal(a.Event)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'Event': %w", err)
		}
	}

	if a.EventId != nil {
		object["EventId"], err = json.Marshal(a.EventId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'EventId': %w", err)
		}
	}

	if a.ItemId != nil {
		object["ItemId"], err = json.Marshal(a.ItemId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ItemId': %w", err)
		}
	}

	if a.Name != nil {
		object["Name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'Name': %w", err)
		}
	}

	if a.NotificationId != nil {
		object["NotificationId"], err = json.Marshal(a.NotificationId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'NotificationId': %w", err)
		}
	}

	if a.NotificationType != nil {
		object["NotificationType"], err = json.Marshal(a.NotificationType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'NotificationType': %w", err)
		}
	}

	if a.ServerId != nil {
		object["ServerId"], err = json.Marshal(a.ServerId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ServerId': %w", err)
		}
	}

	if a.UserId != nil {
		object["UserId"], err = json.Marshal(a.UserId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'UserId': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
